apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: nhd0bf5zm-java-quarkus
  janus-idp.io/tekton: nhd0bf5zm-java-quarkus
  backstage.io/kubernetes-id: nhd0bf5zm-java-quarkus
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: nhd0bf5zm-java-quarkus
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
